name: WebRTC Release
run-name: WebRTC Release
on: repository_dispatch
jobs:
  Build-Script:
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Running WebRTC weekly release checks
        run: |
          sh clean.sh
          pip install requests python-telegram-bot
          python -u scripts/release.py
      - run: echo "🍏 This job's status is ${{ job.status }}."
